# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(Sin, yin, xin, xsin, Gin) {
    .Call('_ProbReco_test', PACKAGE = 'ProbReco', Sin, yin, xin, xsin, Gin)
}

